version = 0.1
[default]
[default.build]
[default.build.parameters]
template_file = "template.yaml"

[default.local_start_api]
[default.local_start_api.parameters]
port = 3000
host = "127.0.0.1"
warm_containers = "EAGER"
