import { FaqItem } from "@/features/pitch/sections/FaqSection/components/FaqItem";

const faqs = [
  {
    number: "1",
    question: "How does AltGrade score borrowers who have zero bureau credit history or CIBIL score?",
    answer:
      "Traditional banks require historical credit card or personal loan records that 400 million Indians simply do not have. AltGrade analyzes verified everyday economic signals instead: daily UPI merchant QR inflows, vendor inventory invoices, electricity meter payments, GST filings, and agricultural mandi receipts. These granular cashflow velocities provide a much more accurate picture of solvency and willingness to pay than a blank credit file.",
  },
  {
    number: "2",
    question: "How does AltGrade protect borrower data privacy under the DPDP Act 2023?",
    answer:
      "We practice radical data minimization. Raw bank statements and personal SMS logs are never persisted on central servers. Underwriting features are derived via zero-knowledge proofs and local edge computation. Consent is granular, purpose-bound, and expires automatically once the loan evaluation decision is completed, fulfilling all Digital Personal Data Protection Act and RBI directives.",
  },
  {
    number: "3",
    question: "What is Mitra and how does vernacular voice underwriting work?",
    answer:
      "Mitra is our conversational AI credit officer built specifically for Bharat. Rather than forcing applicants through complex multi-page English forms, Mitra speaks with borrowers in 14 regional Indian languages including Hindi, Tamil, Telugu, Bengali, and Marathi. Mitra understands dialectal nuances, helps applicants explain irregular seasonal income, and clearly states loan interest rates and repayment schedules.",
  },
  {
    number: "4",
    question: "How do lending partners and NBFCs integrate with the AltGrade protocol?",
    answer:
      "NBFCs and scheduled commercial banks connect to AltGrade through RESTful Open Credit Enablement Network (OCEN) APIs and standardized Loan Origination System (LOS) webhooks. Underwriting assessments return within 300 milliseconds, complete with credit limits, recommended interest bands, and full mathematical feature attribution dossiers.",
  },
  {
    number: "5",
    question: "How does AltGrade handle seasonal farming cycles and temporary business hardship?",
    answer:
      "Bharat's economy does not operate on rigid corporate paydays. Micro-retailers and smallholder farmers experience seasonal fluctuations due to monsoons, festival stocking, and harvest times. AltGrade continuously calibrates cashflow baselines and proactively suggests flexible restructuring: extending tenures or converting monthly lump sums into micro-daily deductions before defaults happen.",
  },
  {
    number: "6",
    question: "Is AltGrade an NBFC or a software protocol?",
    answer:
      "AltGrade is a pure technology and alternate underwriting protocol. We partner with regulated entities including RBI-licensed NBFCs, small finance banks, and rural cooperative banks who provide institutional balance sheet capital, while AltGrade provides the intelligence, fraud prevention, and applicant onboarding layer.",
  },
  {
    number: "7",
    question: "What documents does a micro-merchant need to apply for working capital?",
    answer:
      "Zero physical paperwork is required. An applicant needs only their smartphone, an active UPI QR merchant account or bank account, and DigiLocker-linked Aadhaar or PAN for instant digital KYC. The entire assessment takes less than three minutes from initial scan to sanction.",
  },
  {
    number: "8",
    question: "How does AltGrade eliminate demographic and gender bias in AI decisions?",
    answer:
      "Our underwriting models are continuously audited using SHAP (Shapley Additive Explanations) and counterfactual fairness benchmarks. PII attributes such as religion, caste, gender, and specific geographical markers are mathematically isolated from the risk vector to guarantee that only genuine economic reliability influences the credit score.",
  },
  {
    number: "9",
    question: "Where is applicant data hosted and processed?",
    answer:
      "All computation, data storage, and model inference reside exclusively within AWS sovereign data centers in Mumbai and Hyderabad. Zero financial or biometric telemetry ever leaves Indian sovereign territory, strictly following Reserve Bank of India data localization guidelines.",
  },
  {
    number: "10",
    question: "How can applicants improve their AltGrade score if initially declined?",
    answer:
      "AltGrade never issues a blunt, unexplained rejection. Every decision includes an actionable counterfactual roadmap generated by Mitra: for example, maintaining 45 days of consistent UPI merchant settlement, timely utility bill payments, or linking verified supplier invoices to unlock credit eligibility.",
  },
];

export const FaqList = () => {
  return (
    <div
      role="region"
      aria-label="Frequently Asked Questions"
      className="border-t border-[#2F5527]/25 flex flex-col w-full"
    >
      {faqs.map((faq) => (
        <FaqItem
          key={faq.number}
          number={faq.number}
          question={faq.question}
          answer={faq.answer}
          defaultOpen={faq.number === "1"}
        />
      ))}
    </div>
  );
};